<a href="https://colab.research.google.com/github/ruthpeter/BE_Project_final/blob/master/finalSegregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from PIL import Image
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K
from keras.models import model_from_json
import tensorflow as tf


Using TensorFlow backend.


In [0]:
def read_img(location):
  path = os.path.abspath('.cnn.py') #absolute path of program
  path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file 
  print(path)
  x_train = []
  y_train = []
  x_test = []
  y_test = []
  dirs = os.listdir(path+'drive/My Drive/UCMerced_LandUse/Images/')
  print(dirs)
  label = 0
  for i in dirs:
    n = 0
    count = 0
    for pic in glob.glob(path+'drive/My Drive/UCMerced_LandUse/Images/'+i+'/*.tif'):
      im = Image.open(pic)
      im = np.array(im)
      if((im.shape[0]==256) and (im.shape[1] ==256) and count < 99): 
        r = im[:,:,0]
        g = im[:,:,1]
        b = im[:,:,2]
        if(n<5): # 5 data in beginning set as test data
          x_test.append([r,g,b])
          y_test.append([label])
        else: #remaining data set as training data
          x_train.append([r,g,b])
          y_train.append([label])
        n = n + 1
        count = count + 1
    label = label + 1
  return np.array(x_train),np.array(y_train),np.array(x_test),np.array(y_test)



In [0]:
def test_img(location):
  path = os.path.abspath('.cnn.py') #absolute path of program
  path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file
  x_test=[]
  y_test=[]
  im = Image.open(path+'e006.tiff')
  im = np.array(im)
  print(im.shape[0])
  if((im.shape[0]==256) and (im.shape[1] ==256)): 
			r = im[:,:,0]
			g = im[:,:,1]
			b = im[:,:,2]
			x_test.append([r,g,b])
			y_test.append(17)
  return np.array(x_test),np.array(y_test)


In [0]:


img_rows = 256
img_cols = 256
num_class = 21
x_train,y_train,x_test,y_test = read_img('drive/My Drive/UCMerced_LandUse/Images/')

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)


input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)



# model = Sequential()
# model.add(Conv2D(32,kernel_size=(3, 3),activation='relu',input_shape=input_shape))

# #model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=input_shape))

# model.add(MaxPooling2D(pool_size=(2,2)))
# model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
# #model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))

# #model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
# #model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))


# model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# #model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
# #model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
# model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# #model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
# #model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
# model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# model.add(Dropout(0.25))
# model.add(Flatten())
# model.add(Dropout(0.25))
# model.add(Dense(512, activation='relu'))
# model.add(Dense(512, activation='relu'))
# model.add(Dense(21, activation='softmax'))


model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), padding='same', activation='relu',input_shape=input_shape))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

model.add(tf.keras.layers.Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))


#model.add(tf.keras.layers.BatchNormalization(input_shape=x_train.shape[1:]))
model.add(tf.keras.layers.Conv2D(128, (3, 3), padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2,2)))
#model.add(tf.keras.layers.Dropout(0.25))

#model.add(tf.keras.layers.BatchNormalization(input_shape=x_train.shape[1:]))
model.add(tf.keras.layers.Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
#model.add(tf.keras.layers.Dropout(0.25))

#model.add(tf.keras.layers.BatchNormalization(input_shape=x_train.shape[1:]))
model.add(tf.keras.layers.Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2,2)))
#model.add(tf.keras.layers.Dropout(0.25))

model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(512))
model.add(tf.keras.layers.Activation('relu'))
#model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(512))
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Dense(21))
model.add(tf.keras.layers.Activation('softmax'))
#model.summary()

# model.compile(
#       optimizer='adam',
#       loss='categorical_crossentropy',
#       metrics=['acc'])



/content/


KeyboardInterrupt: ignored

U-net demo 

In [0]:
from __future__ import division

import numpy as np
from keras.models import Model
from keras.layers import Input
from keras.layers.convolutional import Conv2D, MaxPooling2D, UpSampling2D, Cropping2D
from keras.layers.merge import concatenate

from keras import backend as K
from keras.layers import Activation

import cv2

from keras.layers.normalization import BatchNormalization

from keras.optimizers import Nadam
import pandas as pd

from keras.callbacks import ModelCheckpoint, History
import os

from keras.models import model_from_json
import datetime


In [0]:
!pip install tifffile

    100% |████████████████████████████████| 133kB 6.4MB/s 


In [0]:

import matplotlib.pyplot as plt
import numpy as np
import cv2
import pandas as pd
from shapely.wkt import loads as wkt_loads
import tifffile as tiff
import os
import random
from keras.models import Model
from keras.layers import Input, merge, Convolution2D, MaxPooling2D, UpSampling2D, Reshape, core, Dropout ,Flatten
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras import backend as K
from sklearn.metrics import jaccard_similarity_score
from shapely.geometry import MultiPolygon, Polygon
import shapely.wkt
import shapely.affinity
from collections import defaultdict

In [0]:
def pixel_softmax(y_true, y_pred):
   y_pred = K.reshape(y_pred, (-1, num_mask_channels))
   y_true = K.reshape(y_true, (-1, num_mask_channels))
   return K.mean(K.categorical_crossentropy(y_pred, y_true, from_logits=True))


def ConvBN2(x, num_filter, stride_size=3):
    x = Conv2D(num_filter, (stride_size, stride_size), padding='same', kernel_initializer='he_uniform')(x)
    x = BatchNormalization()(x)
    x = Activation('selu')(x)
    x = Conv2D(num_filter, (stride_size, stride_size), padding='same', kernel_initializer='he_uniform')(x)
    x = BatchNormalization()(x)
    x = Activation('selu')(x)
    return x

In [0]:
import numpy as np 
import pandas as pd 
import os
import cv2
from tqdm import tqdm

from keras.models import Sequential, Model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D, BatchNormalization, Input, merge, UpSampling2D, Cropping2D, ZeroPadding2D, Reshape, core, Convolution2D
from keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
from keras import optimizers
from keras import backend as K
from keras.optimizers import SGD
from keras.layers.merge import concatenate

from sklearn.metrics import fbeta_score
from sklearn.model_selection import train_test_split

In [0]:
from tensorflow.contrib.keras import models
from tensorflow.contrib.keras import layers 

img_rows = 256
img_cols = 256
num_class = 21
x_train,y_train,x_test,y_test = read_img('drive/My Drive/UCMerced_LandUse/Images/')

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)


input_shape = (img_rows, img_cols,3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)


class UNet():
    def __init__(self):
        print ('build UNet ...')

    def get_crop_shape(self, target, refer):
        # width, the 3rd dimension
        cw = (target.get_shape()[2] - refer.get_shape()[2]).value
        assert (cw >= 0)
        if cw % 2 != 0:
            cw1, cw2 = int(cw/2), int(cw/2) + 1
        else:
            cw1, cw2 = int(cw/2), int(cw/2)
        # height, the 2nd dimension
        ch = (target.get_shape()[1] - refer.get_shape()[1]).value
        assert (ch >= 0)
        if ch % 2 != 0:
            ch1, ch2 = int(ch/2), int(ch/2) + 1
        else:
            ch1, ch2 = int(ch/2), int(ch/2)

        return (ch1, ch2), (cw1, cw2)

    def create_model(self, img_shape, num_class):

        concat_axis = 3
        inputs = layers.Input(shape = img_shape)

        conv1 = layers.Conv2D(32, (3, 3), activation='relu', padding='same', name='conv1_1')(inputs)
        conv1 = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(conv1)
        pool1 = layers.MaxPooling2D(pool_size=(2, 2))(conv1)
        conv2 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(pool1)
        conv2 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(conv2)
        pool2 = layers.MaxPooling2D(pool_size=(2, 2))(conv2)

        conv3 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(pool2)
        conv3 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(conv3)
        pool3 = layers.MaxPooling2D(pool_size=(2, 2))(conv3)

        conv4 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(pool3)
        conv4 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(conv4)
        pool4 = layers.MaxPooling2D(pool_size=(2, 2))(conv4)

        conv5 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
        conv5 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(conv5)

        up_conv5 = layers.UpSampling2D(size=(2, 2))(conv5)
        ch, cw = self.get_crop_shape(conv4, up_conv5)
        crop_conv4 = layers.Cropping2D(cropping=(ch,cw))(conv4)
        up6 = layers.concatenate([up_conv5, crop_conv4], axis=concat_axis)
        conv6 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(up6)
        conv6 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(conv6)

        up_conv6 = layers.UpSampling2D(size=(2, 2))(conv6)
        ch, cw = self.get_crop_shape(conv3, up_conv6)
        crop_conv3 = layers.Cropping2D(cropping=(ch,cw))(conv3)
        up7 = layers.concatenate([up_conv6, crop_conv3], axis=concat_axis) 
        conv7 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(up7)
        conv7 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(conv7)

        up_conv7 = layers.UpSampling2D(size=(2, 2))(conv7)
        ch, cw = self.get_crop_shape(conv2, up_conv7)
        crop_conv2 = layers.Cropping2D(cropping=(ch,cw))(conv2)
        up8 = layers.concatenate([up_conv7, crop_conv2], axis=concat_axis)
        conv8 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(up8)
        conv8 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(conv8)

        up_conv8 = layers.UpSampling2D(size=(2, 2))(conv8)
        ch, cw = self.get_crop_shape(conv1, up_conv8)
        crop_conv1 = layers.Cropping2D(cropping=(ch,cw))(conv1)
        up9 = layers.concatenate([up_conv8, crop_conv1], axis=concat_axis)
        conv9 = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(up9)
        conv9 = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(conv9)

        ch, cw = self.get_crop_shape(inputs, conv9)
        conv9 = layers.ZeroPadding2D(padding=((ch[0], ch[1]), (cw[0], cw[1])))(conv9)
        #conv10 = layers.Conv2D(num_class, (1, 1))(conv9)
        
        
        flatten =keras.layers.Flatten()(conv9)
        Dense1 = Dense(512, activation='relu')(flatten)
        BN =BatchNormalization() (Dense1)
        Dense2 = Dense(21, activation='softmax')(BN)

        model = models.Model(inputs=inputs, outputs=conv10)

        return model
      
    def get_unet(self,n_ch,patch_height,patch_width):
      
        concat_axis = 3

        inputs = Input((patch_height, patch_width, n_ch))

        conv1 = Conv2D(32, (3, 3), padding="same", name="conv1_1", activation="relu", data_format="channels_last")(inputs)
        #conv1 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv1)
        pool1 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv1)
        
        conv2 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool1)
        #conv2 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv2)
        pool2 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv2)

        conv3 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool2)
        #conv3 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv3)
        #pool3 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv3)

#         conv4 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool3)
#         #conv4 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv4)
#         pool4 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv4)

#         conv5 = Conv2D(512, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool4)
#         #conv5 = Conv2D(512, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv5)

#         up_conv5 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv5)
#         ch, cw = self.get_crop_shape(conv4, up_conv5)
#         crop_conv4 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv4)
#         up6   = concatenate([up_conv5, crop_conv4], axis=concat_axis)
#         conv6 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(up6)
#         #conv6 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv6)

#         up_conv6 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv6)
#         ch, cw = self.get_crop_shape(conv3, up_conv6)
#         crop_conv3 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv3)
#         up7   = concatenate([up_conv6, crop_conv3], axis=concat_axis)
#         conv7 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(up7)
#         #conv7 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv7)

#         up_conv7 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv7)
#         ch, cw = self.get_crop_shape(conv2, up_conv7)
#         crop_conv2 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv2)
#         up8   = concatenate([up_conv7, crop_conv2], axis=concat_axis)
#         conv8 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(up8)
#         #conv8 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv8)

#         up_conv8 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv8)
#         ch, cw = self.get_crop_shape(conv1, up_conv8)
#         crop_conv1 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv1)
#         up9   = concatenate([up_conv8, crop_conv1], axis=concat_axis)
#         conv9 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(up9)
#         #conv9 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv9)

#         #ch, cw = get_crop_shape(inputs, conv9)
#         #conv9  = ZeroPadding2D(padding=(ch[0],cw[0]), data_format="channels_last")(conv9)
#         #conv10 = Conv2D(1, (1, 1), data_format="channels_last", activation="sigmoid")(conv9)


        up_conv3 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv3)
        ch, cw = self.get_crop_shape(conv2, up_conv3)
        crop_conv2 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv2)
        up4   = concatenate([up_conv3, crop_conv2], axis=concat_axis) 
        conv4 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(up4)
          
        up_conv4 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv4)
        ch, cw = self.get_crop_shape(conv1, up_conv4)
        crop_conv1 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv1)
        up5   = concatenate([up_conv4, crop_conv1], axis=concat_axis) 
        conv5 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(up5)
        
        
        flatten =  Flatten()(conv5)
        Dense1 = Dense(128, activation='relu')(flatten)
        BN =BatchNormalization() (Dense1)
        Dense2 = Dense(21, activation='sigmoid')(BN)

        model = Model(input=inputs, output=Dense2)

        return model



hello = UNet()


model = hello.get_unet(3, 256, 256)
#model = hello.create_model(input_shape,21)


# model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Convolution2D(32, (3, 3),activation='relu',input_shape=input_shape))
# #model.add(tf.keras.layers.Conv2D(32, (3, 3),activation='relu'))
# model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

# model.add(tf.keras.layers.Conv2D(64, (3, 3),activation='relu'))
# #model.add(tf.keras.layers.Conv2D(64, (3, 3),activation='relu'))
# model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))


# model.add(tf.keras.layers.Conv2D(128, (3, 3),activation='relu'))
# #model.add(tf.keras.layers.Conv2D(128, (3, 3),activation='relu'))
# model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

# model.add(tf.keras.layers.Conv2D(256, (3, 3),activation='relu'))
# #model.add(tf.keras.layers.Conv2D(256, (3, 3),activation='relu'))
# model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

# #model.add(tf.keras.layers.Conv2D(512, (3, 3),activation='relu'))
# model.add(tf.keras.layers.Conv2D(512, (3, 3),activation='relu'))

# model.add(tf.keras.layers.UpSampling2D(size=(2, 2)))
# model.add(tf.keras.layers.Conv2D(256, (3, 3),activation='relu'))

# model.add(tf.keras.layers.UpSampling2D(size=(2, 2)))
# model.add(tf.keras.layers.Conv2D(128, (3, 3),activation='relu'))

# model.add(tf.keras.layers.UpSampling2D(size=(2, 2)))
# model.add(tf.keras.layers.Conv2D(64, (3, 3),activation='relu'))

# model.add(tf.keras.layers.UpSampling2D(size=(2, 2)))




/content/
['parkinglot', 'storagetanks', 'runway', 'sparseresidential', 'river', 'overpass', 'tenniscourt', 'mobilehomepark', 'beach', 'buildings', 'freeway', 'golfcourse', 'harbor', 'chaparral', 'intersection', 'denseresidential', 'mediumresidential', 'forest', 'baseballdiamond', 'airplane', 'agricultural']
(1946, 3, 256, 256)
(1946, 1)
(105, 3, 256, 256)
(105, 1)
build UNet ...


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:192: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`


In [0]:
# TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
# tf.logging.set_verbosity(tf.logging.INFO)

# tpu_model = tf.contrib.tpu.keras_to_tpu_model(
#     model,
#     strategy=tf.contrib.tpu.TPUDistributionStrategy(
#         tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))


if 'COLAB_TPU_ADDR' not in os.environ:
  print('ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!')
else:
  tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']
  print ('TPU address is', tpu_address)

  with tf.Session(tpu_address) as session:
    devices = session.list_devices()
    
  print('TPU devices:')
  print(devices)

TPU address is grpc://10.38.33.42:8470
TPU devices:
[_DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:CPU:0, CPU, -1, 11577002308664079222), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 5635832503111318103), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 9665912832239048173), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 10040119896148797786), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 5133137750359844171), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 13659516597524339813), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 12284649909342530000), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 1841613888373672532), _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 16309168400290056244)

In [0]:
# TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
# tf.logging.set_verbosity(tf.logging.INFO)

# tpu_model = tf.contrib.tpu.keras_to_tpu_model(
#     model,
#     strategy=tf.contrib.tpu.TPUDistributionStrategy(
#         tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))

print(tpu_address)
tf.logging.set_verbosity(tf.logging.INFO)

# tpu_model = tf.contrib.tpu.keras_to_tpu_model(
#     model,
#     strategy=tf.contrib.tpu.TPUDistributionStrategy(
#         tf.contrib.cluster_resolver.TPUClusterResolver(tpu_address)))    
# # tpu_model = tf.contrib.tpu.keras_to_tpu_model(
# #     model,strategy
# #    )
    
tpu_model = tf.contrib.tpu.keras_to_tpu_model(
        model,
        strategy=tf.contrib.tpu.TPUDistributionStrategy(
            tf.contrib.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
        )
    )
tpu_model.compile(
        optimizer=tf.train.AdamOptimizer(0.001),
        loss=tf.keras.losses.categorical_crossentropy,
        metrics=['accuracy']
    )


# tpu_model.fit(x_train, y_train, batch_size=64, nb_epoch=100, verbose=1, validation_data=(x_test, y_test))
# loss, acc = model.evaluate(x_test, y_test, verbose=0)

# tpu_model.summary()

# print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))

grpc://10.38.33.42:8470

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Querying Tensorflow master (grpc://10.38.33.42:8470) for TPU system metadata.
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 11577002308664079222)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 5635832503111318103)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 9665912832239048173)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replic

ValueError: ignored

In [0]:
# model.compile(
#         optimizer=tf.train.AdamOptimizer(0.001),
#         loss=tf.keras.losses.categorical_crossentropy,
#         metrics=['accuracy']
#     )

model.compile(loss='binary_crossentropy', # We NEED binary here, since categorical_crossentropy l1 norms the output before calculating loss.
                  optimizer=tf.train.AdamOptimizer(0.001),
                  metrics=['accuracy'])

In [0]:
# model.fit(x_train, y_train, batch_size=50, nb_epoch=3, verbose=50, validation_data=(x_test, y_test))
# print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))

# loss, acc = model.evaluate(x_test, y_test, verbose=0)

# model.summary()

model.fit(x = x_train, y= y_train, validation_data=(x_test, y_test),
          batch_size=16, verbose=1, epochs=10, shuffle=True)


loss, acc = model.evaluate(x_test, y_test, verbose=0)


# model.fit(x_train, y_train, batch_size=64, nb_epoch=10, verbose=1, validation_data=(x_test, y_test))
# loss, acc = model.evaluate(x_test, y_test, verbose=0)




model.summary()

print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))


Instructions for updating:
Use tf.cast instead.
Train on 1946 samples, validate on 105 samples
Epoch 1/10
1946/1946 [==============================] - 92s 47ms/step - loss: 0.4710 - acc: 0.8578 - val_loss: 0.2362 - val_acc: 0.9537
Epoch 2/10
1946/1946 [==============================] - 77s 40ms/step - loss: 0.1646 - acc: 0.9538 - val_loss: 0.2174 - val_acc: 0.9274
Epoch 3/10
1946/1946 [==============================] - 77s 40ms/step - loss: 0.1268 - acc: 0.9573 - val_loss: 0.2515 - val_acc: 0.9528
Epoch 4/10
1946/1946 [==============================] - 77s 40ms/step - loss: 0.0874 - acc: 0.9679 - val_loss: 0.2958 - val_acc: 0.9220
Epoch 5/10
1946/1946 [==============================] - 77s 39ms/step - loss: 0.0568 - acc: 0.9824 - val_loss: 0.8583 - val_acc: 0.7098
Epoch 6/10
1946/1946 [==============================] - 77s 39ms/step - loss: 0.0331 - acc: 0.9935 - val_loss: 0.6147 - val_acc: 0.9546
Epoch 7/10
1946/1946 [==============================] - 78s 40ms/step - loss: 0.0198 - ac

In [0]:
from keras.models import model_from_json
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")


NameError: ignored

In [0]:
img_rows = 256
img_cols = 256
num_class = 21

In [0]:
from keras.models import model_from_json

# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
 
x_demo,y_demo = test_img('content/')
print("x-demo")
print(x_demo)
  
x_demo = x_demo.reshape(x_demo.shape[0], img_rows, img_cols, 3)

x_demo = x_demo.astype('float32')
x_demo /= 255
y_demo = keras.utils.to_categorical(y_demo, 21)

# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['mae', 'acc'])
print(y_demo)
y_prob = loaded_model.predict(x_demo)
y_classes = y_prob.argmax(axis=-1)
print(y_classes)
score = loaded_model.evaluate(x_demo, y_demo, verbose=1)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

Loaded model from disk
256
x-demo
[[[[ 2 27 68 ... 44 48 45]
   [ 6 44 65 ... 72 52 57]
   [ 6 25 27 ... 82 71 66]
   ...
   [91 87 81 ... 12 16 17]
   [71 58 60 ... 14 26 21]
   [35 11 29 ... 45 57 36]]

  [[ 2 29 69 ... 50 52 46]
   [ 7 45 66 ... 78 57 58]
   [11 28 28 ... 87 76 69]
   ...
   [92 88 80 ... 13 18 19]
   [74 61 63 ... 17 30 23]
   [42 19 37 ... 48 61 42]]

  [[ 3 31 72 ... 45 50 45]
   [ 6 45 69 ... 77 57 60]
   [ 6 27 30 ... 93 79 72]
   ...
   [90 85 77 ...  8 15 19]
   [73 60 62 ...  9 23 19]
   [44 19 37 ... 37 49 31]]]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[17]
1/1 [==============================] - 0s 176ms/step
mean_absolute_error: 4.80%
